In [6]:
#http://ailaby.com/tfidf/
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

np.set_printoptions(precision=2)
docs = np.array([
    '白 黒 赤',  #文書1
    '白 白 黒', #文書2
    '白 黒 黒 黒', #文書3
    '白' #文書4
])

vectorizer = TfidfVectorizer(use_idf=True, token_pattern=u'(?u)\\b\\w+\\b')
vecs = vectorizer.fit_transform(docs)
print(vecs.toarray())


[[0.4  0.77 0.49]
 [0.85 0.   0.52]
 [0.26 0.   0.96]
 [1.   0.   0.  ]]
